site_name: Version Control Manager(VCM) Documentation
nav:
  - Home: index.md
  - Source Code: src.md
  - Test(s): tests.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - toc.integrate
